export const USER_STATUS = {
  UNCONFIRMED: 'UNCONFIRMED',
  CONFIRMED: 'CONFIRMED',
  ARCHIVED: 'ARCHIVED',
  UNKNOWN: 'UNKNOWN',
  RESET_REQUIRED: 'RESET_REQUIRED',
  FORCE_CHANGE_PASSWORD: 'FORCE_CHANGE_PASSWORD',
} as const;

export type UserStatus = (typeof USER_STATUS)[keyof typeof USER_STATUS];
